{{- if .Values.managedServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "filebeat.serviceAccount" . }}-cluster-role
{{ include "filebeat.labels" $ | indent 2}}
rules: {{ toYaml .Values.clusterRoleRules | nindent 2 -}}
{{- end -}}
