{{ range $name, $config_scope := dict "" .Values "-daemonset" .Values.daemonset "-deployment" .Values.deployment }}
{{- if and $config_scope.filebeatConfig (or (eq $name "") $config_scope.enabled) -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "filebeat.fullname" $ }}{{ $name }}-config
  labels:
    app: "{{ template "filebeat.fullname" $ }}"
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    heritage: {{ $.Release.Service | quote }}
    release: {{ $.Release.Name | quote }}
data:
{{- range $path, $config := $config_scope.filebeatConfig }}
  {{ $path }}: |
    {{- toYaml $config | nindent 4 -}}
{{- end -}}
{{ end }}
{{ end }}
