{{- if .Values.daemonset.enabled }}
{{- with (merge .Values.daemonset .Values) }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
{{ include "filebeat.metadata" (dict "values" . "root" $) | indent 2 }}
spec:
  updateStrategy:
    {{- if eq .updateStrategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .maxUnavailable }}
    {{- end }}
    type: {{ .updateStrategy }}
{{ include "filebeat.podmeta" (dict "values" . "root" $) | indent 2 }}
    spec:
      tolerations: {{ toYaml .tolerations | nindent 8 }}
      nodeSelector: {{ toYaml .nodeSelector | nindent 8 }}
      {{- if .priorityClassName }}
      priorityClassName: {{ .priorityClassName  }}
      {{- end }}
      affinity: {{ toYaml .affinity | nindent 8 }}
      serviceAccountName: {{ template "filebeat.serviceAccount" $ }}
      terminationGracePeriodSeconds: {{ .terminationGracePeriod }}
      {{- if .hostNetworking }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      {{- if .dnsConfig }}
      dnsConfig: {{ toYaml .dnsConfig | nindent 8 }}
      {{- end }}
      {{- if .hostAliases }}
      hostAliases: {{ toYaml .hostAliases | nindent 8 }}
      {{- end }}
      volumes:
      {{- range .secretMounts }}
      - name: {{ .name }}
        secret:
          secretName: {{ .secretName }}
      {{- end }}
      {{- if .filebeatConfig }}
      - name: filebeat-config
        configMap:
          defaultMode: 0600
          name: {{ template "filebeat.fullname" $ }}-daemonset-config
      {{- end }}
      - name: data
        hostPath:
          path: {{ .hostPathRoot }}/{{ template "filebeat.fullname" $ }}-{{ $.Release.Namespace }}-data
          type: DirectoryOrCreate
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
      {{- if .dockerSockMount }}
      - name: varrundockersock
        hostPath:
          path: /var/run/docker.sock
      {{- end }}
      {{- if .extraVolumes }}
{{ toYaml .extraVolumes | indent 6 }}
      {{- end }}
      {{- if .imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .imagePullSecrets | indent 8 }}
      {{- end }}
      securityContext: {{ toYaml .podSecurityContext | nindent 10 }}
      {{- if .extraInitContainers }}
      initContainers:
      # All the other beats accept a string here while
      # filebeat accepts a valid yaml array. We're keeping
      # this as a backwards compatible change, while adding
      # also a way to pass a string as other templates to
      # make these implementations consistent.
      # https://github.com/elastic/helm-charts/issues/490
      {{- if eq "string" (printf "%T" .extraInitContainers) }}
{{ tpl .extraInitContainers . | indent 8 }}
      {{- else }}
{{ toYaml .extraInitContainers | indent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: "filebeat"
        image: "{{ .image }}:{{ .imageTag }}"
        imagePullPolicy: "{{ .imagePullPolicy }}"
        args:
        - "-e"
        - "-E"
        - "http.enabled=true"
        {{- range .extraArgs }}
          - {{ . | quote }}
        {{- end }}
        livenessProbe:
{{ toYaml .livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .readinessProbe | indent 10 }}
        resources:
{{ toYaml .resources | indent 10 }}
        securityContext:
          readOnlyRootFilesystem: true
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
{{- if .extraEnvs }}
{{ toYaml .extraEnvs | indent 8 }}
{{- end }}
        envFrom: {{ toYaml .envFrom | nindent 10 }}
        volumeMounts:
        {{- range .secretMounts }}
        - name: {{ .name }}
          mountPath: {{ .path }}
          {{- if .subPath }}
          subPath: {{ .subPath }}
          {{- end }}
        {{- end }}
        {{- range $path, $config := .filebeatConfig }}
        - name: filebeat-config
          mountPath: /usr/share/filebeat/{{ $path }}
          readOnly: true
          subPath: {{ $path }}
        {{- end }}
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlog
          mountPath: /var/log
          readOnly: true
        # Necessary when using autodiscovery; avoid mounting it otherwise
        # See: https://www.elastic.co/guide/en/beats/filebeat/master/configuration-autodiscover.html
        {{- if .dockerSockMount }}
        - name: varrundockersock
          mountPath: /var/run/docker.sock
          readOnly: true
        {{- end }}
        {{- if .extraVolumeMounts }}
{{ toYaml .extraVolumeMounts | indent 8 }}
        {{- end }}
      {{- if .extraContainers }}
      # Currently some extra blocks accept strings
      # to continue with backwards compatibility this is being kept
      # whilst also allowing for yaml to be specified too.
      {{- if eq "string" (printf "%T" .extraContainers) }}
{{ tpl .extraContainers . | indent 6 }}
      {{- else }}
{{ toYaml .extraContainers | indent 6 }}
      {{- end }}
      {{- end }}
{{- end }}
{{- end }}
