# Deploy singleton instance in the whole cluster for some unique data sources, like aws input
{{- if .Values.deployment.enabled }}
{{- with (merge .Values.deployment .Values) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
{{ include "filebeat.metadata" (dict "values" . "root" $) | indent 2 }}
spec:
  replicas: {{ .replicas }}
{{ include "filebeat.podmeta" (dict "values" . "root" $) | indent 2 }}
    spec:
      affinity: {{ toYaml .affinity | nindent 8 }}
      nodeSelector: {{ toYaml .nodeSelector | nindent 8 }}
      {{- if .hostAliases }}
      hostAliases: {{ toYaml .hostAliases | nindent 8 }}
      {{- end }}
       # Gen
      tolerations: {{ toYaml .tolerations | nindent 8 }}
      {{- if .priorityClassName }}
      priorityClassName: {{ .priorityClassName  }}
      {{- end }}
      serviceAccountName: {{ template "filebeat.serviceAccount" $ }}
      terminationGracePeriodSeconds: {{ .terminationGracePeriod }}
      volumes:
      {{- range .secretMounts }}
      - name: {{ .name }}
        secret:
          secretName: {{ .secretName }}
      {{- end }}
      {{- if .filebeatConfig }}
      - name: filebeat-config
        configMap:
          defaultMode: 0600
          name: {{ template "filebeat.fullname" $ }}-deployment-config
      {{- if .extraVolumes }}
{{ toYaml .extraVolumes | indent 6 }}
      {{- end }}
      {{- if .imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .extraInitContainers }}
      initContainers:
      # All the other beats accept a string here while
      # filebeat accepts a valid yaml array. We're keeping
      # this as a backwards compatible change, while adding
      # also a way to pass a string as other templates to
      # make these implementations consistent.
      # https://github.com/elastic/helm-charts/issues/490
      {{- if eq "string" (printf "%T" .extraInitContainers) }}
{{ tpl .extraInitContainers . | indent 6 }}
      {{- else }}
{{ toYaml .extraInitContainers | indent 6 }}
      {{- end }}
      {{- end }}
      securityContext: {{ toYaml  .podSecurityContext | nindent 10 }}
      containers:
      - name: "filebeat"
        image: "{{.image }}:{{ .imageTag }}"
        imagePullPolicy: "{{ .imagePullPolicy }}"
        args:
          - "-e"
          - "-E"
          - "http.enabled=true"
          - "-E"
          - "http.host=$(POD_IP)"
        {{- range .extraArgs }}
          - {{ . | quote }}
        {{- end }}
        livenessProbe:
{{ toYaml .livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .readinessProbe | indent 10 }}
        resources: {{ toYaml .resources | nindent 10 }}
        securityContext:
          readOnlyRootFilesystem: true
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_ID
          valueFrom:
            fieldRef:
              fieldPath: status.PodIP
{{- if .extraEnvs }}
{{ toYaml .extraEnvs | indent 8 }}
{{- end }}
        envFrom: {{ toYaml .envFrom | nindent 10 }}
        volumeMounts:
        {{- range .secretMounts }}
        - name: {{ .name }}
          mountPath: {{ .path }}
          {{- if .subPath }}
          subPath: {{ .subPath }}
          {{- end }}
        {{- end }}
        {{- range $path, $config := .filebeatConfig }}
        - name: filebeat-config
          mountPath: /usr/share/filebeat/{{ $path }}
          readOnly: true
          subPath: {{ $path }}
        {{- end }}
        {{- if .extraVolumeMounts }}
{{ toYaml .extraVolumeMounts | indent 8 }}
        {{- end }}
      {{- if .extraContainers }}
      # Currently some extra blocks accept strings
      # to continue with backwards compatibility this is being kept
      # whilst also allowing for yaml to be specified too.
      {{- if eq "string" (printf "%T" .extraContainers) }}
{{ tpl .extraContainers $ | indent 6 }}
      {{- else }}
{{ toYaml .extraContainers | indent 6 }}
      {{- end }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
