name: publish chart
on:
  push:
    tags-ignore:
      - 'v?[1-8].*.*' # Ignore tags released before forking from the official Elastic chart

permissions:
  contents: read
  packages: write

jobs:
  validate:
    uses: .github/workflows/validate.yml
  publish_chart:
    name: Publish new tag
    needs:
      - validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@${{ github.ref_name }}

    - name: Push Helm chart to OCI compatible registry (Github)
      uses: bsord/helm-push@4.1.0
      with:
        useOCIRegistry: true
        registry-url:  oci://ghcr.io/${{ github.repository }}
        username: ${{ github.repository_owner }}
        access-token: ${{ secrets.GITHUB_TOKEN }}
        chart-folder: .
